server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "kibana_system"
elasticsearch.password: "sOsjEk7U08DOfPzeHmPb"

xpack.security.encryptionKey: "something_at_least_32_characters"

xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"