version: "3"
volumes:
  elk:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\Work\Docker\ELK\share
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: sem_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elk:/home/elk
      - ./common/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: sem_kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - elk:/home/elk
      - ./common/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: sem_logstash
    depends_on:
      - elasticsearch
    volumes:
      - elk:/home/elk
      - ./common/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./common/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./common/logstash/pipeline/rac_index.conf:/usr/share/logstash/pipeline/rac_index.conf